services:
  - type: web
    name: chemlit-ai
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DEEPSEEK_API_KEY
        value: sk-511ac6fc938f4654a6b05b6160828260
      - key: QWEN_API_KEY
        value: sk-cbda5a5d6c0f43288409d5243d06cd89
